_wandb:
    value:
        cli_version: 0.24.2
        e:
            h6hc32cq0jwjifpj1ryteee8l8lhn2pa:
                args:
                    - --local_rank=0
                    - ./projects/configs/stage1_track_map/base_track_map_front.py
                    - --launcher
                    - pytorch
                    - --deterministic
                    - --work-dir
                    - ./projects/work_dirs/stage1_track_map/base_track_map_front/
                codePath: tools/train.py
                codePathLocal: tools/train.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "858574028800"
                        used: "408556990464"
                email: ziz359@ucsd.edu
                executable: /usr/bin/python
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-e088be5e-b6ee-4f91-6477-4ec8683423f8
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-75ba3942-006b-d4b9-572c-2787dc62a902
                host: zihan-intentpred-debug2-79dd867f77-8qzwq
                memory:
                    total: "540893765632"
                os: Linux-6.8.0-94-generic-x86_64-with-glibc2.29
                program: ./tools/train.py
                python: CPython 3.8.10
                root: /zihan-west-vol/UniAD
                startedAt: "2026-02-17T11:22:31.557129Z"
                writerId: h6hc32cq0jwjifpj1ryteee8l8lhn2pa
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 9
                - 37
                - 38
                - 41
                - 53
                - 60
            "2":
                - 1
                - 5
                - 9
                - 37
                - 38
                - 41
                - 53
                - 60
            "3":
                - 13
                - 16
                - 61
            "4": 3.8.10
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
work_dir:
    value: /zihan-west-vol/UniAD/projects/work_dirs/stage1_track_map/base_track_map_front
